# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d40da46752504ce1d534da18ecc430ba84c2494977c6cca2f2d0ecfc028954ef8e3bdf9ddd5b2af264de5f4ed815004aac9d407bea3712f7f34b494f91bd7439

test:
  secret_key_base: 1d5705240472fc540616aba2f5f90a0d52405aeb6cf51e1408b39ebd6b90db8c4f8e3c7b332a5a45d483543432a4d57c60a5a3e949019b92ea98b9eff070c030

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
